#!/bin/bash
# =============================================================================
# Reachy Mini Audio Routing — Setup
#
# Run this once to detect your external audio hardware and save the
# configuration. Re-run if you change external devices.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
# =============================================================================

set -euo pipefail

CONFIG_DIR="$HOME/.config/reachy-audio"
CONFIG_FILE="$CONFIG_DIR/devices.conf"

echo "============================================"
echo "  Reachy Mini External Audio Setup"
echo "============================================"
echo ""

# Check pactl is available
if ! command -v pactl &>/dev/null; then
    echo "ERROR: pactl not found."
    echo "Install it with:  sudo apt install pulseaudio-utils"
    echo "  or (PipeWire):  sudo apt install pipewire-pulse"
    exit 1
fi

# ---- List output devices (sinks) ----
echo "=== Available OUTPUT devices (speakers) ==="
echo ""

declare -a SINK_NAMES=()
declare -a SINK_DESCS=()
idx=0

while IFS=$'\t' read -r _pa_idx name _driver; do
    desc=$(pactl list sinks 2>/dev/null | awk -v n="$name" '
        /Name:/ && $NF == n { found=1 }
        found && /Description:/ { sub(/.*Description: /, ""); print; exit }
    ')
    desc="${desc:-$name}"
    SINK_NAMES+=("$name")
    SINK_DESCS+=("$desc")
    echo "  [$idx] $desc"
    echo "       ($name)"
    echo ""
    idx=$((idx + 1))
done < <(pactl list short sinks 2>/dev/null)

if [ ${#SINK_NAMES[@]} -eq 0 ]; then
    echo "  No output devices found. Is PulseAudio running?"
    exit 1
fi

echo ""
read -rp "Enter the number for your EXTERNAL SPEAKER: " sink_choice

if ! [[ "$sink_choice" =~ ^[0-9]+$ ]] || [ "$sink_choice" -ge ${#SINK_NAMES[@]} ]; then
    echo "ERROR: Invalid selection."
    exit 1
fi

CHOSEN_SINK="${SINK_NAMES[$sink_choice]}"
CHOSEN_SINK_DESC="${SINK_DESCS[$sink_choice]}"

echo ""
echo "Selected speaker: $CHOSEN_SINK_DESC"
echo ""

# ---- List input devices (sources, skip monitors) ----
echo "=== Available INPUT devices (microphones) ==="
echo ""

declare -a SRC_NAMES=()
declare -a SRC_DESCS=()
idx=0

while IFS=$'\t' read -r _pa_idx name _driver; do
    desc=$(pactl list sources 2>/dev/null | awk -v n="$name" '
        /Name:/ && $NF == n { found=1 }
        found && /Description:/ { sub(/.*Description: /, ""); print; exit }
    ')
    desc="${desc:-$name}"
    SRC_NAMES+=("$name")
    SRC_DESCS+=("$desc")
    echo "  [$idx] $desc"
    echo "       ($name)"
    echo ""
    idx=$((idx + 1))
done < <(pactl list short sources 2>/dev/null | grep -v '\.monitor')

if [ ${#SRC_NAMES[@]} -eq 0 ]; then
    echo "  No input devices found. Is PulseAudio running?"
    exit 1
fi

echo ""
read -rp "Enter the number for your EXTERNAL MICROPHONE: " src_choice

if ! [[ "$src_choice" =~ ^[0-9]+$ ]] || [ "$src_choice" -ge ${#SRC_NAMES[@]} ]; then
    echo "ERROR: Invalid selection."
    exit 1
fi

CHOSEN_SOURCE="${SRC_NAMES[$src_choice]}"
CHOSEN_SOURCE_DESC="${SRC_DESCS[$src_choice]}"

echo ""
echo "Selected microphone: $CHOSEN_SOURCE_DESC"
echo ""

# ---- Save configuration ----
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# Reachy Mini External Audio Configuration
# Generated by setup.sh on $(date)
# Re-run setup.sh to change these values.

# External speaker (PulseAudio sink name)
EXTERNAL_SINK="$CHOSEN_SINK"
EXTERNAL_SINK_DESC="$CHOSEN_SINK_DESC"

# External microphone (PulseAudio source name)
EXTERNAL_SOURCE="$CHOSEN_SOURCE"
EXTERNAL_SOURCE_DESC="$CHOSEN_SOURCE_DESC"
EOF

echo "============================================"
echo "  Configuration saved!"
echo "============================================"
echo ""
echo "  Speaker : $CHOSEN_SINK_DESC"
echo "  Mic     : $CHOSEN_SOURCE_DESC"
echo "  Config  : $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Stop the ElevenLabs app from the dashboard"
echo "  2. Run: ./external-audio-on.sh"
echo "  3. Start the ElevenLabs app from the dashboard"
echo ""
